# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb4d6a325bcec4eda7a880df6add2971157b66dacbc64979e2617573cc7d5141396b4a27f58b072e170b07f9419d43c2ed607187a7412932550538aaff1ed97

test:
  secret_key_base: 80879ea378467f4bc077bff8fca5fe8cab618974725ac30ee62f365b88c2369f438bcb996282f8ca8235bca0123d80829bb92c54198d8c3b33eb761a3a5b4cc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
